### PR TITLE
server session BUGFIX where crypt_r is not available

### PR DESCRIPTION
**Pull request by mislavn**
Hi,

I encountered a portability issue with uclibc in OpenWrt. This patched fixed my problem and it has been tested on an older OpenWrt build (uclibc), on the latest Lede build (musl) and in docker (ubuntu 16.04).

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
that seems fine except I would have initially used `crypt` if it was correct. With your patch if 2 user get to authenticate at the exact same time and `crypt` gets called simultaneously, it will likely crash. It would be better to think about some other solution that will not break thread-safety.

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

@michalvasko is it enough if I add locks to the function auth_password_compare_pwd() just for the case when crypt_r is not defined?

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
yeah, that should work fine for cases where `crypt_r` cannot be used.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
seems ok except I don't see any initialization of the lock, so just initialize it statically and it should be ready to be merged.

Regards,
Michal

**Comment by mislavn** [comment]
Done.

**Pull request merged**
