### PR TITLE
Feature/cmake export config

### PR DESCRIPTION
**Pull request by ClausKlein**
cmakelint all cmake files too
fix errors in cmake modules used.
revent compile errors if libcrypt is not availeable on BSD/OSX

see too https://github.com/Bagira80/More-Modern-CMake

**NOTE**: at least _cmake v3.13_ is required!

The cmake config files are exported now to be later used:
````
-- Installing: /usr/local/lib/cmake/libnetconf2/libnetconf2-config-version.cmake
-- Installing: /usr/local/lib/cmake/libnetconf2/libnetconf2-targets.cmake
-- Installing: /usr/local/lib/cmake/libnetconf2/libnetconf2-targets-release.cmake
-- Installing: /usr/local/lib/cmake/libnetconf2/libnetconf2-config.cmake
````

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
sorry for not replaying sooner but it seemed to me this was not a critical pull request.

Firstly, please change the base branch to `devel`, we do not accept pull request to `master` anymore. Now, as you wrote (and that I was afraid of), these changes require *cmake* 3.13 which we simply cannot yet require for *libnetconf2*, it is too soon (as seeing that, for example, the very recent CentOS 8 has only *cmake* 3.11, it is still years away for being available on all the distributions).

However, it seems to me that many of the changes you made do not require the new *cmake* and are mostly improvements and minor fixes and so if you are willing, you can keep only those and I will be happy to merge them.

Regards,
Michal

**Comment by ClausKlein** [comment]
Ok, I will try if it works. fetchcontent was first added in v3.11 (about 3 years old!)
https://cmake.org/cmake/help/latest/release/3.11.html?highlight=fetchcontent#modules

**Comment by ClausKlein** [comment]
by the way, do you know cmakelint?

```shell
Claus-MBP:libnetconf2 clausklein$ find . -name CMakeLists.txt | xargs cmakelint
Total Errors: 0
Claus-MBP:libnetconf2 clausklein$ find . -name '*.cmake' | xargs cmakelint
./CMakeModules/FindCMocka.cmake:0: Find modules should use uppercase names; consider using FindCMOCKA.cmake [convention/filename]
./CMakeModules/FindLibSSH.cmake:0: Find modules should use uppercase names; consider using FindLIBSSH.cmake [convention/filename]
./CMakeModules/FindLibVAL.cmake:0: Find modules should use uppercase names; consider using FindLIBVAL.cmake [convention/filename]
./CMakeModules/FindLibYANG.cmake:0: Find modules should use uppercase names; consider using FindLIBYANG.cmake [convention/filename]
./CMakeModules/FindPackageVersionCheck.cmake:0: Find modules should use uppercase names; consider using FindPACKAGEVERSIONCHECK.cmake [convention/filename]
./CMakeModules/FindPackageVersionCheck.cmake:0: Package should include FindPackageHandleStandardArgs [package/consistency]
./CMakeModules/FindPackageVersionCheck.cmake:0: Package should use FIND_PACKAGE_HANDLE_STANDARD_ARGS [package/consistency]
./CMakeModules/uninstall.cmake:27: Expression repeated inside endforeach; better to use only endforeach() [readability/logic]
./FindLibNETCONF2.cmake:0: Find modules should use uppercase names; consider using FindLIBNETCONF2.cmake [convention/filename]
./FindLibNETCONF2.cmake:39: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:39: Extra spaces between 'if' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:41: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:42: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:42: Extra spaces between 'else' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:42: Expression repeated inside else; better to use only else() [readability/logic]
./FindLibNETCONF2.cmake:44: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:57: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:72: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:72: Extra spaces between 'if' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:73: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:75: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:76: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:77: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:78: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:79: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:79: Extra spaces between 'else' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:79: Expression repeated inside else; better to use only else() [readability/logic]
./FindLibNETCONF2.cmake:80: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:81: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:81: Extra spaces between 'endif' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:81: Expression repeated inside endif; better to use only endif() [readability/logic]
./FindLibNETCONF2.cmake:83: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:84: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:87: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:89: Do not mix upper and lower case commands [readability/mixedcase]
./FindLibNETCONF2.cmake:89: Extra spaces between 'endif' and its () [whitespace/extra]
./FindLibNETCONF2.cmake:89: Expression repeated inside endif; better to use only endif() [readability/logic]
./FindLibNETCONF2.cmake:0: Package should include FindPackageHandleStandardArgs [package/consistency]
./FindLibNETCONF2.cmake:0: Package should use FIND_PACKAGE_HANDLE_STANDARD_ARGS [package/consistency]
Total Errors: 39
Claus-MBP:libnetconf2 clausklein$ 
```

**Comment by michalvasko** [comment]
Hi,
no, I don't. But the errors are reasonable and I think I write `cmake` files without any of these problems now. `FindLibNETCONF2.cmake` was written in 2015.

Regards,
Michal

**Pull request closed without merging**
